
services:
  emotion_service:
    build:
      context: ./emotion_service
      dockerfile: Dockerfile
      
    ports:
      - "5000:5000"
    
    networks:
      - "mynetwork"

    
  recomendation_service:
    build:
      context: ./recommendation_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
